name: Azure Functions

on:
  push:
    branches:
      - "main"
  pull_request:
    branches: 
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core v5.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.x
        
    - name: Setup .NET Core v3.x
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.x

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: |
        cd GitTrends.Functions
        dotnet build --configuration Release --no-restore
