name: Xamarin

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: 
      - "*"

jobs:
  
    UnitTests_Android_iOS:
      runs-on: macos-latest
      env:
        GetTestTokenApiKey: ${{ secrets.GetTestTokenApiKey }}
        GetSyncFusionInformationApiKey: ${{ secrets.GetSyncFusionInformationApiKey }}
        GetNotificationHubInformationApiKey: ${{ secrets.GetNotificationHubInformationApiKey }}
      steps:
      - uses: actions/checkout@v1
      - name: UnitTests_Android_iOS
        run: |
          nuget restore
          
          chmod -R 777 ./GitTrends.Android/appcenter-pre-build.sh
          ./GitTrends.Android/appcenter-pre-build.sh

          UnitTestProject=`find ./ -name GitTrends.UnitTests.csproj`
          echo $UnitTestProject

          UnitTestDirectory=`dirname $UnitTestProject`
          echo $UnitTestDirectory
          
          dotnet test  -c "Release" $UnitTestDirectory
          
          msbuild ./GitTrends.Android/GitTrends.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Release     

          # Use iOS simulator until GitHub Actions adds iOS Certificates & Provisioning Profiles
          msbuild ./GitTrends.Android/GitTrends.iOS.csproj /verbosity:normal /t:Rebuild /p:Configuration=Release /p:Platform=iPhoneSimulator    
          


#    iOS:
#      runs-on: macos-latest
#      steps:
#      - uses: actions/checkout@v1
#      - name: iOS
#        run: |
#          nuget restore
#          msbuild GitTrends.iOS/GitTrends.iOS.csproj /verbosity:normal /t:Rebuild /p:Platform=iPhone /p:Configuration=Release
